"""Added new fields in subscribe model

Revision ID: 294ad93dd83a
Revises: 7fcb2b0fd473
Create Date: 2024-06-23 12:58:11.024747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294ad93dd83a'
down_revision: Union[str, None] = '7fcb2b0fd473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments_history', sa.Column('telegram_payment_charge_id', sa.String(length=64), nullable=True))
    op.add_column('payments_history', sa.Column('provider_payment_charge_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments_history', 'provider_payment_charge_id')
    op.drop_column('payments_history', 'telegram_payment_charge_id')
    # ### end Alembic commands ###
