"""CHAR to VARCHAR

Revision ID: 7fcb2b0fd473
Revises: 64fe5bf689d7
Create Date: 2024-06-16 18:31:25.667734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcb2b0fd473'
down_revision: Union[str, None] = '64fe5bf689d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribes', 'name',
               existing_type=sa.CHAR(length=128),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribes', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.CHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
